### ISSUE TITLE
Underwater Splashes

### ISSUE THREAD

**Issue by s1lenced7** [OreCruncher/Environs#2]
Seems like i occasionally have splash effects underwater, not sure what info i can provide to help on this one 

![image](https://user-images.githubusercontent.com/60624013/74092446-44690480-4ac4-11ea-9025-bf6d1aeea231.png)

**Comment by OreCruncher** [comment]
There is probably an air gap down there.  How often does this occur?

**Comment by s1lenced7** [comment]
![image](https://user-images.githubusercontent.com/60624013/74092976-fbb54980-4acb-11ea-9786-534577969145.png)

Quite often actually, this time no air gap, just me standing underwater. it's paired with overlapping splashing sounds at high volume. I'm sorry i can only describe the issue :/

**Comment by OreCruncher** [comment]
That's fine.  I see what I needed to see in the last screenshot.  You see those 3 dots to the lower left of your player?  It's a water splash.  What this is telling me is that the ripples are being generated on top of the a water source block because the particle will hit water.  The irony in this is that I am working on this problem at this very moment. :)

**Comment by s1lenced7** [comment]
Okido 👍

**Comment by OreCruncher** [comment]
Pushed release build 0.1.0.0 to CurseForge
